---
title: "amigos_facebook"
author: "vinicius"
date: "23 de fevereiro de 2018"
output: html_document
---

```{r setup, include=FALSE}
library(rJava)
library("xlsx")
library(ggplot2)


# Your task is to investigate the distribution of your friends'
# birth months and days.

# Here some questions you could answer, and we hope you think of others.

# **********************************************************************

# How many people share your birthday? Do you know them?
# (Reserve time with them or save money to buy them a gift!)

# Which month contains the most number of birthdays?

# How many birthdays are in each month?

# Which day of the year has the most number of birthdays?

# Do you have at least 365 friends that have birthdays on everyday
# of the year?

# **********************************************************************

# You will need to do some data munging and additional research to
# complete this task. This task won't be easy, and you may encounter some
# unexpected challenges along the way. We hope you learn a lot from it though.

# You can expect to spend 30 min or more on this task depending if you
# use the provided data or obtain your personal data. We also encourage you
# to use the lubridate package for working with dates. Read over the documentation
# in RStudio and search for examples online if you need help.

# You'll need to export your Facebooks friends' birthdays to a csv file.
# You may need to create a calendar of your Facebook friends' birthdays
# in a program like Outlook or Gmail and then export the calendar as a
# csv file.

# Once you load the data into R Studio, you can use the strptime() function
# to extract the birth months and birth days. We recommend looking up the
# documentation for the function and finding examples online.

# We've included some links in the Instructor Notes to help get you started.

# Once you've completed your investigation, create a post in the discussions
# that includes:
#   1. any questions you answered, your observations, and summary statistics
#   2. snippets of code that created the plots
#   3. links to the images of your plots

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation below the line. Submit it when you are ready.
# ===============================================================================



birthday <- read.csv("birthdaysExample.csv", header=TRUE)
#quantidade de pessoas que compartilharam 
length(birthday$dates)
#converte o character para date
birthday$new <- strptime(x = birthday$dates, format = "%m/%d/%y")
#cria um dataframe
df <- data.frame(date = birthday$new,
year = as.numeric(format(birthday$new, format = "%Y")),
month = as.numeric(format(birthday$new, format = "%m")),
day = as.numeric(format(birthday$new, format = "%d")),
month_day = as.numeric(format(birthday$new, format = "%j")))# %j converte para dias do ano entre 1-366

```


Abaixo percebemos que o mês 03 possui maior número de aniversariantes
```{r}
qplot(x = month, data = df, binwidth = 1) +
  scale_x_continuous(breaks = seq(1, 13, 1),lim = c(1, 13)) 
```

Percebemos que o dia 14 possui o maior número de aniversariantes
```{r}
qplot(x = day, data = df,binwidth = 1) +
  scale_x_continuous(breaks = seq(1, 32, 1),lim = c(1, 32)) 
```

O total de pessoas que compartilham a mesma data de aniversário comigo:
```{r}
nrow(subset(df, df$day == 26 & df$month == 03))
```


Podemos visualizar que todos os dias do ano possui aniversário
```{r}
qplot(x = df$month_day, data = df, binwidth = 1) +
scale_x_discrete(breaks=1:366)
```

O total de aniversários em cada mês:
```{r}
table(df$month)
```




